export const POST_CATEGORY = 'POST_CATEGORY';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CONFERENCES = 'SET_CONFERENCES';
export const SET_TEAMS = 'SET_TEAMS';
export const SET_HOVERED_CATEGORY = 'SET_HOVERED_CATEGORY';
export const SET_HOVERED_CONFERENCE = 'SET_HOVERED_CONFERENCE';
export const SET_SELECTED_ADMIN_CATEGORY = 'SET_SELECTED_ADMIN_CATEGORY';
export const SET_CURRENT_ADMIN_BUTTON_PANEL = 'SET_CURRENT_ADMIN_BUTTON_PANEL';