export const POST_CATEGORY = 'POST_CATEGORY';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CONFERENCES = 'SET_CONFERENCES';
export const SET_TEAMS = 'SET_TEAMS';
export const SET_IS_CONFERENCES_OPENED = 'SET_IS_CONFERENCES_OPENED';
export const SET_IS_TEAMS_OPENED = 'SET_IS_TEAMS_OPENED';
export const SET_HOVERED_CATEGORY = 'SET_HOVERED_CATEGORY';
export const SET_HOVERED_CONFERENCE = 'SET_HOVERED_CONFERENCE';