export const SET_BANNERS = 'SET_BANNERS';
export const SET_BANNERS_STATUS = 'SET_BANNERS_STATUS';
export const CLOSE_NEW_BANNER = 'CLOSE_NEW_BANNER';
export const SET_NEW_BANNER_CATEGORY = 'SET_NEW_BANNER_CATEGORY';
export const POST_BANNER = 'POST_BANNER';
export const ADD_NEW_BANNER = 'ADD_NEW_BANNER';
export const ADD_NEW_BANNER_IMG = 'ADD_NEW_BANNER_IMG';
export const UPDATE_NEW_BANNER = 'UPDATE_NEW_BANNER';
export const GET_BANNERS = 'GET_BANNERS';
export const SELECT_BANNER = 'SELECT_BANNER';
export const UPDATE_BANNER_LOCALIZATION = 'UPDATE_BANNER_LOCALIZATION';
export const DELETE_BANNER_LOCALIZATION = 'DELETE_BANNER_LOCALIZATION';
export const UPDATE_BANNER_LOCALIZATION_HEADLINE = 'UPDATE_BANNER_LOCALIZATION_HEADLINE';
export const ADD_BANNER_LOCALIZATION = 'ADD_BANNER_LOCALIZATION';


