export const SET_IS_LOADING = 'MAIN_ARTICLES/SET_IS_LOADING';
export const SET_MAIN_ARTICLES = 'MAIN_ARTICLES/SET_MAIN_ARTICLES';
export const SET_CURRENT_ARTICLE = 'MAIN_ARTICLES/SET_CURRENT_ARTICLE';
